version: "3"
services:
  cronjob:
    build:
      context: ../..
      dockerfile: dapp-playwright/docker/Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - GIT_USER_NAME=${GIT_USER_NAME}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL}
    container_name: cronjob_service
    restart: always
    volumes:
      - ../../dapp-playwright:/app/dapp-playwright:cached
      - ../../.git:/app/.git
      - /app/dapp-playwright/node_modules
    env_file:
      - ../../dapp-playwright/.env # 빌드 컨텍스트(root/)에서 .env 파일의 경로